
name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - run: chmod +x gradlew
        name: "Set Permissions"
      - run: ./gradlew clean
        name: "Clean"
      - run: ./gradlew bootJar
        name: "Boot JAR"
      - uses: actions/upload-artifact@v2
        with:
          name: Bot
          path: build/libs/*.jar
